numarray = [["Inpredictafinity", "‡", "3.50"],
["Instafinity", "Ɒ", "3.502"],
["Corrupfinity", "ᴓ", "3.504"],
["Unifinity", "⟐", "3.52"],
["Omega-Prosgegrammenifinity", "ῼ", "3.521"],
["Omega-Psili-Perispomenifinity", "Ὦ", "3.55"],
["Psifinity", "ᴪ", "3.60"],
["Pamphylian-Digammafinity", "Ͷ ", "3.65"],
["Archaic-Sampifinity", "Ͳ", "3.66"],
["Unixfinity", "∫", "3.75"],
["Existensfinity", "֍", "3.80", [["The Medallion", "🎖️"]]],
["Endingfinity", "𝔈", "3.90"],
["Krandingfinity", "𝔊", "3.92"],
["Never", "ↇ", "4.00", [["[???]", "[name is symbol]"], ["The Indefinite Barrier", "ᛉ"]]],
["Huggest", "[no symbol]", "4.01"],
["Everythingfinity", "ↀ", "4.02"],
["True Finality", "ᥤ", "4.03"],
["Ever / Alwayfinity", "ↂ", "4.04"],
["Unreachifinity", "ↆ", "4.045"],
["Insiderfinity", "Ɨ", "4.075", [["Always", "❩"]]],
["Redifinity", "⨛", "4.0875"],
["Circifinity", "○", "4.092"],
["Oneilitialifinity", "❶", "4.11", [["Ever", "ↀ"]]],
["Erkifinity", "ᘒ ", "4.135"],
["Enderiumfinity", "ↈ", "4.142"],
["Mercurifinity", "𐰦", "4.15"],
["Marsifinity", "▩", "4.16"],
["Alphaifinity", "𐰤", "4.175"],
["Mortalfinity", "𐰵", "4.19"],
["Absolute Existence", "✵", "4.22"],
["Too Much Massive Finity", "⋻ 1 & 2 {Finite}", "4.25", [["THE ABSOLUTE BIGGEST TRUE VERY SUPER DUPER ERROR END", "[no symbol]"], ["Collapsefinity (DoDeca's scale)", "ς"]]],
["Absolute One Fintitility", "*ϴ* - 1", "4.27"],
["Googolilfinity", "1 / 2 Of Ordinals of Finity Entarial", "4.285"],
["A Absolute Plus of Finite", "1 [FINITY] [+]", "4.30", [["Perpetual One (DoDeca's scale)", "PER(1)"]]],
["Googol-M-Infinity", "[៳]", "4.31"],
["Finite Null", "л0", "4.325"],
["Cardinal Null", "𝗖", "4.33", [["Finalityfinity", "ᥤ"]]],
["Omnifinity", "ດ", "4.34"],
["Not So Finite", "1 & 2 [Finite]", "4.35"],
["Eternity Restart", "⬲", "4.36"],
["Multisesmic", ":ວ:", "4.37"],
["Prestige True Finity", "[△] - FINITY", "4.40"],
["Sophifinity", "[MultiFinity] - 1 // 2^1", "4.46"],
["Metaverse Finite", "{已} - 1", "4.47"],
["Super Barrel Finite", "☐", "4.476"],
["Complex-Universe-HYDRO", "[・] - 1 • 2", "4.484"],
["Barrelifinity Finite", "[⍏]", "4.49"],
["Absolute Null Finite", "[ヘ]", "4.497"],
["Tratitic One", "キ1", "4.504"],
["Argonitisic One", "⬲1", "4.51"],
["Omni Absolute Numbers", "Os(2)", "4.517"],
["Goosupergol Finity", "1 丅 2 Ordinals of Clustered Finity", "4.55"],
["Prestige Collapsing Null Ending", "〖刁〗", "4.562"],
["Tressical Finite X", "xX 口 xX", "4.57"],
["Quantum Finity Number One", "X○○X", "4.578"],
["Eternal Array Point", "ብxXဘ", "4.586"],
["Omni Ordinals", "ཡ七𐍉", "4.60"],
["Mesoictipint One", "ユ xX ユ", "4.62"],
["Gigaictipint", "ユ_ユ xX ユ_ユ", "4.63"],
["Exatitimin", "ֆ௹", "4.65"],
["Windinamic", "[个仗] xX", "4.656"],
["Hydronamic Ordinal", "ҢㅐxX", "4.665"],
["Celestial A", "⊂_A", "4.677"],
["Universfinity", "ནᑂ", "4.692"],
["The Everlasting True Number of All Existence", "ಉ", "4.74"],
["One Star Number", "[☆]", "4.75"],
["Kilolute Infinity", "Ω☆", "4.78"],
["Megalute Infinity", "Ω☆☆", "4.785"],
["Lutilute Infinity", "Ω☆_☆^☆☐", "4.791"],
["Essential Endingly One", "Ψ(E)¹", "4.80"],
["Bronnicistal-Infinity", "る^る", "4.81"],
["Petisiczinc", "১^コ", "4.815"],
["Super-Collapsing Numeral", "△^コ", "4.8125"],
["Rintesnic", "ᗜ_Ʊ", "4.82"],
["Yattisomic", "ᗛᗚ", "4.829"],
["Idestinite", "ᗛᗆᗉᗚ", "4.832"],
["Sestrmic Finite", "⋑⎠人", "4.838"],
["Finitititiy", "忚^Ǿ_忸忷", "4.85"],
["Jirulousilifinitity", "悤悆^恲_恹ᴭ悙", "4.851"],
["Kilotinite", "Κ_ꞤͰ", "4.856"],
["Absolute Astinite", "B^℺_⅊Ẑ", "4.859"],
["Absolute Breaking Super Logic", "[equation]", "4.86"],
["Absolute X of Ending", "[equation]", "4.861"],
["Hyperlouslute One", "[equation]", "4.864"],
["Equatllic of One", "[equation]", "4.869"],
["Recyclility One", "🔂_1^🔁", "4.875"],
["Velstibility", "[equation]", "4.88"],
["Ordinalility Null", "[equation]", "4.883"],
["Absolute Doublutitious", "[equation]", "4.886"],
["Haratutlute One", "[equation]", "4.89"],
["Absolute Not Delta", "[equation]", "4.892"],
["Error Number One", "[equation]", "4.893"],
["Meta Error Sulute One", "[equation]", "4.895"],
["Meta Error Sulute Sulute One", "[equation]", "4.898"],
["Hyperfinity - Sulute - All", "[equation]", "4.899"],
["Type III Number", "[equation]", "4.90"],
["Eco Typilit-finity", "[equation]", "4.91"],
["Finitebarrierility", "[equation]", "4.917"],
["Omnipolarisbarrierility", "[equation]", "4.922"],
["Border of Finiteility", "[equation]", "4.928"],
["Galacticility Everything", "[equation]", "4.932"],
["Astitype of Numerals", "[equation]", "4.935"],
["Omnithility", "⟁⟌⟌⟜◼", "4.941"],
["The Nanticility Error", "[equation]", "4.947"],
["Error-Fility-NAN", "[equation]", "4.95"],
["Finalistsicbility", "[equation]", "4.953"],
["Yearlinity Numberfinite", "[equation]", "4.959"],
["The Great Heavenfinite", "[equation]", "4.963"],
["The True Kiloend", "[equation]", "4.968"],
["The Super Godility", "[equation]", "4.97"],
["True Everything of Godlous", "[equation]", "4.974"],
["Omega Gods of Everything", "[equation]", "4.977"],
["Absolute Godlous", "[equation]", "4.98"],
["Endless", "ᚖ / ⟠", "5.00", [["The Bugendai Mathie", "ヂ"], ["The Zenless Barrier", "Ꙁ"], ["The Interdimensional Monstrosity", "⎆"], ["The Mystery of Ends", "Ø^[?]1"], ["Absolute Totality (DoDeca)", "𝓟"], ["Rotation Revolution", "↻ℂ"]]],
["True Endless", "⧈", "5.001", [["Repeated Endless", "⟠_⟠"], ["Endless (True Undefined)", "⟠"]]],
["Endless-Quality", "▥", "5.0015", [["Endless of True Complexity", "⟠{2,A x⊙}⟠"], ["True Endless (True Undefined)", "⧈"]]],
["Endless-Aniolity Cirniutnia", "◒", "5.002", [["Iota Function", "Ι"], ["Endless-Quality (True Undefined)", "▥"]]],
["Endfull", "🟔", "5.00225"],
["True Gods", "🟃", "5.0025", [["Neverless", "⍄"], ["Endless-Aniolity Cirniutnia (True Undefined)", "◒"]]],
["Endiluminosity", "Ꮏ", "5.0032"],
["Squendinlity", "[untypable symbol]", "5.005"],
["Infinity-Insta-Bility", "∾", "5.007"],
["Finite-Insta-Bility", "[untypable symbol]", "5.01"],
["Termicuous", "[untypable symbol]", "5.012"],
["N.E.V.E.R E.V.E.R!!!", "[untypable symbol]", "5.015"],
["Too every-Massive Finium", "▧ 1 $ 2 [Finium]", "5.021"],
["Endful", "[untypable symbol]", "5.025", [["The Absolute Finity", "{Finity} 1 - 2"]]],
["Ordinal Level Centuple Stack", "OL(. x 100", "5.033"],
["Super-Everything", "[untypable symbol]", "5.04"],
["Super Ordinal Level Endless-uple Stack", "SOL(. x ᚖ", "5.041"],
["Mega-Everything", "[untypable symbol]", "5.044"],
["Giga-Everything", "[untypable symbol]", "5.046"],
["Tera Ordinal Level 100", "TOL(100)", "5.0468"],
["Peta Ordinal Level 100", "POL(100)", "5.0472"],
["Century Ordinal Level 100", "100-OL(100)", "5.05"],
["Super-Null-(Super-Null-(Super-Null Ordinal Level) Ordinal Level) Ordinal Level 100", "[2➳_[2➳_[2➳OL(100)]OL(100)]OL(100)]", "5.062"],
["Eta-Hyper One Cardinal", "[untypable symbol]", "5.075", [["The-W of Omni", "[W] 1 | 1^2"]]],
["Et-tra-a-Hyper One Cardinal", "[untypable symbol]", "5.08"],
["Et-Ser-a Hyper One Cardinal", "[untypable symbol]", "5.084"],
["Et-Saganjar-a Hyper One Cardinal", "[untypable symbol]", "5.089"],
["The Hard End", "🕈 ⌷ 🕈 ⌷ x 🕈", "5.09"],
["THE END", "[no symbol]", "5.10", [["Absolute-Can-Not-Find-Cardinal-Finite", "ֆ 1 ֆxXք"]]],
["THE END (for real!)", "[no symbol]", "5.102"],
["THE LIMIT", "[no symbol]", "5.105", [["One-Squaredfinity", "[1]"], ["Eternal Last Other Side of Forever", "⨊"]]],
["The Impossible", "[no symbol]", "5.1054"],
["The Barrier", "[no symbol]", "5.1058"],
["The Restart", "⮔", "5.1063"],
["The Forever", "Ⴔ", "5.1068"],
["The Eternal", "[untypable symbol]", "5.1075"],
["The Reality", "[no symbol]", "5.1081"],
["The VOID", "[no symbol]", "5.1089"],
["The Super", "[no symbol]", "5.11"],
["The Supi", "SW△[1,1₁(1,1)]", "5.112", [["True Forever", "⨏"]]],
["The Omni", "[untypable symbol]", "5.115", [["Destiny-Infinite Stagel", "⫐"]]],
["T.R.U.E F.I.N.A.L.E (Terminus of Restart Unity of Ends of Final Isolated Numbers Absolute Legend of Ends)", "[no symbol]", "5.12"],
["Meta-Hyper One Cardinal", "[untypable symbol]", "5.1215"],
["Trans-Hyper One Cardinal", "[untypable symbol]", "5.123"],
["Penta-Hyper One Cardinal", "[untypable symbol]", "5.1241"],
["Hexa-Hyper One Cardinal", "[untypable symbol]", "5.1258"],
["Hepta-Hyper One Cardinal", "[untypable symbol]", "5.1272"],
["End-Eta Hyper One Cardinal", "[untypable symbol]", "5.128"],
["The Transcendence", "[no symbol]", "5.1295"],
["The Ghostify", "[no symbol]", "5.13"],
["THE BIG RIP", "[no symbol]", "5.14"],
["The Ultimate Rebirth", "[untypable symbol]", "5.15", [["Met-Cardinalfinite", "Ⴊ"]]],
["Mathis R.V-finity", "[no symbol]", "5.151"],
["Ultimate Loop #1", "[untypable symbol]", "5.1511"],
["The Eternity Loop #1", "[untypable symbol]", "5.1514"],
["Perpetual One (????[2]-relative)", "PEU*(1)", "5.1515"],
["The Ultimate Beyond", "TUB(1)", "5.1518"],
["The Super-Sam Number", "[no symbol]", "5.1521"],
["Paradoxmeility", "५", "5.1525", [["Conkology", "[no symbol]"], ["Emptinessfinity", "Ꮡ"]]],
["Sunimretility", "[no symbol]", "5.1526"],
["Qalander", "Q^Qal(10^100)", "5.1528"],
["Totality", "山", "5.153"],
["The Great Fish", "[no symbol]", "5.159"],
["Super Sam's Number", "[no symbol]", "5.162"],
["Numifinity", "[no symbol]", "5.173"],
["The Ultimate Cycle", "[no symbol]", "5.178"],
["True Cycle", "[no symbol]", "5.185", [["Endful-Terminus", "Ѻ"], ["Foreverfinite", "μ"]]],
["Outerconst", "[untypable symbol]", "5.22"],
["The Great Function", "α^Finite(1,1)", "5.232"],
["The Beyondility", "[no symbol]", "5.241"],
["Axiomatic Limit (NO!)", "A₀", "5.25"],
["Small Ignorance Ordinal", "♁₀", "5.251"],
["Cetusfinity", "[no symbol]", "5.2517"],
["Homnoion Ordinal", "[no symbol]", "5.2522"],
["Dect Function", "!DꝨꝹ", "5.2526"],
["Deceret Now Cardinal", "[no symbol]", "5.2532"],
["The ??Ordinal", "[no symbol]", "5.2543"],
["Miserable Bypassing the EXAPT", "[no symbol]", "5.255"],
["Bypassed of the Ordinals", "[no symbol]", "5.256"],
["The True Cardinal", "[no symbol]", "5.26", [["The Left-to-Right", "⿰Ѻ⿰"], ["Indefinitefinity", "𖢫"]]],
["The Trardinal", "[no symbol]", "5.261"],
["The Transception", "[no symbol]", "5.2617"],
["One of the Largest Fictional Numbers", "[no symbol]", "5.2622"],
["Travone", "[no symbol]", "5.2628"],
["Mathfinity", "[no symbol]", "5.2634"],
["The True Finity", "ꐟ", "5.2645"],
["Trahrase #1", "[no symbol]", "5.265"],
["The Phrase Function", "[no symbol]", "5.265"],
["The Black Holility", "[no symbol]", "5.266"],
["Transcendfinium", "[no symbol]", "5.268"],
["The Onwards", "[no symbol]", "5.27"],
["Fillifinitillity", "▐  / ┃", "5.275", [["THE TRUE FINAL UNKNOWN", "🙫"]]],
["The Deleveribate", "☆^◇(1)", "5.277"],
["Suksu Null", "ス0[0] or ス0₀", "5.28"],
["The True Layer", "[no symbol]", "5.282"],
["The Finium", "[no symbol]", "5.2829", [["Godly-Terminus", "⦽"]]],
["The Breaking Googoloverse", "[no symbol]", "5.285"],
["The Hyperconinc Finity", "[no symbol]", "5.289"],
["The Infinithing", "[no symbol]", "5.29"],
["Everytrahing", "[no symbol]", "5.292"],
["Metagoogology", "[no symbol]", "5.294"],
["True Undefinitiable", "[no symbol]", "5.295"],
["Circliumize One of Numbers", "[untypable symbol]", "5.30"],
["Transilimizized of Numbers", "[untypable symbol]", "5.308"],
["Metamatramt of True Numbers", "[untypable symbol]", "5.315"],
["Pruelmentize Finite of Numbers", "[untypable symbol]", "5.322"],
["Hexukament Numbers Finity", "[untypable symbol]", "5.334"],
["Trauilnity Breaking Finite Number", "[untypable symbol]", "5.339"],
["Pre-Hyper Ordinalize!", "OR([P])", "5.345"],
["THE MYSTERIOUS", "[no symbol]", "5.35"],
["THE TRUE TYISTERIOUSFINITY", "[no symbol]", "5.359"],
["The Black Finale", "[no symbol]", "5.36"],
["The No End", "[no symbol]", "5.364"],
["The True ????", "[no symbol]", "5.367"],
["The Breaking Nothing", "[no symbol]", "5.373"],
["The True (NO!)", "[no symbol]", "5.378"],
["The True Undefinitable", "[no symbol]", "5.385"],
["The True Lasting", "[no symbol]", "5.392"],
["The F.I.N.A.L.", "⧮", "5.40"],
["The Great Final", "[no symbol]", "5.42"],
["Absolute True Final", "[no symbol]", "5.44"],
["Truest Never of Cyclone Finite of Absolute Everbreaking Existence Omnisity of Final Hadron Everything Forever True Gods of All Infinity Every True Godous Final", "[no symbol]", "5.45"],
["Hadron Everything Forever True Gods of All Infinity Every True Godous Final Truest Never of Cyclone Finite of Absolute Everbreaking Existence Omnisity of Final Hadron Everything Forever True Gods of All Infinity Every True Godous Final Truest Never of Cyclone Finite of Absolute Everbreaking Existence Omnisity of Final Hadron Everything Forever True Gods of All Infinity Every True Godous Final", "[no symbol]", "5.47"],
["The True Omega Finale Reality Everything in the Entire Omni Fictional Dimension Reality Existence", "[no symbol]", "5.49"],
["TRUE F.I.N.A.L-E.N.D.I.N.G / T.H.E F.I.N.A.L E.N.D.I.N.G", "[untypable symbol]", "5.50", [["Conkept", "Э"], ["The Endopoint Inc.", "𖤙"], ["Physics Dimensional One", "ϑ~Љ"]]],
["Firey", "[no symbol]", "5.501"],
["CORRUPTED", "🙫", "5.51"],
["The F.I.N.A.L Stack", "⧈", "5.515"],
["Absolutely N.A.N", "[no symbol]", "5.519"],
["THE U.N.L.I.M.I.T.E.D", "[no symbol]", "5.531"],
["The U.L.T.I.M.A.T.E PHRASE", "[no symbol]", "5.555"],
["The E.N.D E.N.D", "[no symbol]", "5.563"],
["ABSOLUTE D.E.A.T.H", "[no symbol]", "5.569"],
["T.H.E D.E.A.T.H E.N.D", "[no symbol]", "5.575"],
["T..H..E E..N..D", "[no symbol]", "5.60", [["T..H..E U..N..K..N..O..W..N", "[no symbol]"]]],
["Altered F.I.N.A.L", "⧰", "5.65"],
["Refinity", "[no symbol]", "5.66"],
["The Real End (SUPERSCALED)", "✠", "5.68"],
["The Superiounumminus", "[no symbol]", "5.681"],
["THE HALIMUNUNIS", "[untypable symbol]", "5.685", [["Superloops #1", "[no symbol]"]]],
["Exaloops #1", "[no symbol]", "5.6857"],
["Absolute Kilominx of Numbers", "[no symbol]", "5.686"],
["THE GOODBYE", "[no symbol]", "5.689"],
["The .E", "[no symbol]", "5.694"],
["Absolute Meta", "[no symbol]", "5.696"],
["THE E-N-D", "[no symbol]", "5.70"],
["THE BREAKING END", "[no symbol]", "5.73"],
["The Capacity Ending Limit.", "[no symbol]", "5.75", [["Mastered One [Mastery I]", "[no symbol]"], ["The Redi of Meta-Jebel", "ȣʘʙ"]]],
["The Paradox of Numbers", "[no symbol]", "5.765"],
["Mastering Symbols...", "[no symbol]", "5.78"],
["Omnivssunians", "[untypable symbol]", "5.80"],
["GOODBYE OF NUMBERS...", "[no symbol]", "5.85"],
["The True Beyond Gods of all Time of the Terminus Symbols Ever of the Craziest Terminusly Craziest Number Ever", "[no symbol]", "5.95"],
["The Real Final Point", "[untypable symbol]", "6.00", [["\"The End of All Numbers\"", "[untypable symbol]"], ["Spiritual Mastery", "◌̄"], ["The Endility Void of Null", "𖤼"], ["The Finitial Score", "FSc◈⌘⦕1⦖"], ["Phi-Reality of Cardinals", "ಹ2"]]]
["Tarpile-Terminus", "[no symbol]", "6.002"],
["Lacnao-Terminus", "[no symbol]", "6.003"],
["Absolute True Terminus", "[no symbol]", "6.0035"],
["Godly End", "[no symbol]", "6.0038"],
["THE TRUE END OF THE MOST ROLINA COMPLEX END", "[no symbol]", "6.004"],
["Bigfootjinx", "🔯", "6.01"],
["Absolute Endless Finality", "☋", "6.011"],
["The Truest of Cycl-est Gods of Existence", "[untypable symbol]", "6.015"],
["Cuboid-Null Loop (LOE[4/6]-relative)", "[❏]", "6.017"],
["The Demonic God", "[no symbol]", "6.024"],
["Cycle #Cycle", "[no symbol]", "6.03"],
["Uncannibility", "💀", "6.045"],
["The Shape Sequence", "⯄₁", "6.061"],
["PRIME 0", "[no symbol]", "6.067"],
["multizoom(2)", "[name is symbol]", "6.068"],
["E", "[no symbol]", "6.0683"],
["Surpassed of the Integers", "[no symbol]", "6.069"],
["T.H.E F-I-N-A-L-S O_F T$H$E F#I#N#A#L#E", "[no symbol]", "6.0696"],
["The Absolute Limit", "[no symbol]", "6.07"],
["The True Symbol Sequence", "¶1", "6.078"],
["The True Sequence", "Ӷ", "6.083"],
["The Emetresterious", "[no symbol]", "6.088"],
["The Level Phrase Cycle", "[no symbol]", "6.092"],
["ⓤ", "[name is symbol]", "6.095"],
["The Endipoint", "[untypable symbol]", "6.10", [["Ⓑ∑עტ🄽ᗫ ", "[no symbol]"], ["All Universes to the Extreme Point", "Ⰴ⁊Ⰴ"]]],
["WISTFULLY", "፪", "6.15"],
["The Absolute True Final Finite", "[untypable symbol]", "6.16"],
["Huge Collapsing Point", "??[??[2]]", "6.18"],
["Singularity-Ending-Point", "??[??[4]]", "6.181"],
["????[x]", "[name is symbol]", "6.188"],
["????[??]", "[name is symbol]", "6.195"],
["The Plexend", "??[!]", "6.20"],
["The Final Impact", "[no symbol]", "6.22"],
["The True Bypass", "[no symbol]", "6.25"],
["Layeromium #1", "𝔛[1,1]", "6.28"],
["The Absolute Real Limit", "◈", "6.30"],
["The Cycles Breaking Point", "[no symbol]", "6.33"],
["The Cardinality of Finites", "ρF", "6.36"],
["The Inaccessi-Function ~ Level 13", "⦻[13]", "6.40"],
["Numberic Omni Point", "[untypable symbol]", "6.45"],
["ANNIHILATION", "Ⱥ (unofficial)", "6.50", [["The ANNIHILATION of Numbers", "₳"], ["The Mighty Corruption", "₴"], ["TRANSCENDENTAL IMMENSITY", "ೠ"], ["Abterfinitrix", "𑼈"]]],
["The Ascension+", "[no symbol]", "6.501"],
["The Force Limit of Ends", "[no symbol]", "6.505"],
["Bypassed Cardination", "𝖘", "6.51", [["The New Generation of Numbers", "[no symbol]"]]],
["The Everlasting Cardinal", "ঢ", "6.525"],
["In.Finiti.A", "[Ⓐ]", "6.55"],
["Zero to Zero", "[0,0]", "6.58"],
["All.Finities", "⚭", "6.59"],
["First Applical Ordinal", "ⓐ_∆[1]", "6.60"],
["Box Number", "[❒]", "6.625"],
["Inderpowerilin-Class-Finite", "C???[1]⍚???[1]", "6.65"],
["The Novality", "⌑", "6.66"],
["The Mathpoint", "⋇", "6.70"],
["The Mathis", "[߷] x Ω", "6.71"],
["Polaroid Amalgamation", "𒅐", "6.75"],
["The End of Every Single Integer", "ℤ_∅ (unofficial)", "6.80", [["Axis Limit", "ᛰ"], ["Zetasinek", "ရᏝ"]]],
["The Great Beyond", "𝕱", "6.85"],
["The Final Appearance of Numbers", "[no symbol]", "6.90"],
["LIMIT OF ENDINGS", "[no symbol]", "6.99"],
["Limit of Extending", "𖣐 / ᛃ", "7.00", [["The Destiny", "⨚"], ["Mysterious Final Universe", "MFU(1)"], ["The Corrupted Insanity", "吾"], ["Masteried One", "M✬[1]"], ["OMNUS", "Ѻ"], ["Highlightix Venableutitum", "(can't find)"]]],
["Absolute Aperdinal (old)", "Ω∈", "7.01"],
["Liminal Craziness", "LCↇ⇧", "7.012"],
["The True Bottom of Everything In The Entire Omniverse", "[no symbol]", "7.02", [["The Intensity Realm", "IR⤒★"]]],
["Effect of One", "E⤑1 ", "7.035"],
["The First Limitledge", "LL⤑?1 ", "7.048"],
["The True Function", "ᛞ", "7.05"],
["Planck Length One", "[?]-PL▯1", "7.067"],
["The Quark One", "[?]-QU▯1", "7.0825"],
["Pata'Finiuss", "۞", "7.10", [["Perpetual", "[Ω]"], ["The Constructed Limit", "ƛ"]]],
["Moon One", "[?]-15▯1 ", "7.11"],
["ABOVE", "[no symbol]", "7.12"],
["The Circle of Zero", "𐲌-[▯0]-𐲌 ", "7.135"],
["Ultimate Breakdown", "𝕭", "7.175", [["Teardown of Integers", "<[⤓]>(#) "]]],
["True Unbound", "α→α ", "7.182"],
["Absolute Breakdown", "𖥜", "7.20", [["Eternality", "⨋"], ["ØMEGACEPTION", "𐩕"], ["Seperatius", "ꌚ"], ["Limit of Defining", "Ð"]]],
["B.E.Y.O.N.D.", "ᛜ", "7.22", [["Limit of Refining", "Ř"]]],
["The First Cardinal End", "1 [Finite] ᐖ", "7.23", [["ØMEGATION", "𖥚"], ["Tutinicadinary", "(can't find)"], ["Limit of Defying", "Ÿ"]]],
["Numbertomin 1", "[name is symbol]", "7.233"],
["Atomical Breakage", "AB✄○ ", "7.235"],
["The Ultrametidown", "෴", "7.24"],
["X?[0][0] 〒 ???〖3〗⌽ ?⦗2⦘", "[name is symbol]", "7.245"],
["The Googology", "𓊗", "7.25", [["Naetlecadinary", "(can't find)"], ["Efficient Limit Deconstruction", "Ÿ-absolute"]]],
["The Unbreaking End", "ꕟ", "7.26", [["Pochamacadinary", "(can't find)"]]],
["Famicardinarium", "☆➳0", "7.265"],
["The NAN Cardinal", "ꖧ ?", "7.27", [["TEKKANON", "‎𐦟"]]],
["The Cataclysmic Point", "「ॹ」", "7.275"],
["The Unforgiving Limit", "⩞", "7.28"],
["Loop Second", "L^1↻", "7.2875"],
["The Finished", "食か語", "7.29"],
["Vethuva Stage 2", "Vu(2)", "7.295", [["Precipitation", "↯"]]],
["NUKENSTRIUM", "(can't find)", "7.2975"],
["T.H.E U.N.E.N.D.I.N.G P.O.I.N.T", "OiL(𖥜)", "7.30"],
["Everlation Numbress", "ENↂ-0", "7.325"],
["Positive/Negative Point", "+/-", "7.35"],
["Absolute Googology", "ᴑ", "7.40", [["The Light Particulate", "💡₀"], ["The Kalamur", "[untypable symbol]"]]],
["Ordintraium Levels", "Ꙕず / 3 [Finite]", "7.42"],
["The Maxionumfinity", "𝕳", "7.43"],
["THE ULTRA DENSE HIGGS FIELD", "[no symbol]", "7.435"],
["END GAME CALLED", "[untypable symbol]", "7.438"],
["Omnimonstrity", "[untypable symbol]", "7.44", [["Ticonderoga Pennser", "(can't find)"]]],
["Absol", "𖡗", "7.45"],
["The Toxicaion", "[untypable symbol]", "7.50"],
["Maximity", "‎𐱁", "7.60"],
["Numner", "𐋐", "7.65", [["The Kalamur", "𓉔"]]],
["Absolute Cycle", "𐄺", "7.70"],
["Absolute Super Everything", "ꗈ", "7.80"],
["End of Infinities", "[untypable symbol]", "7.90", [["The Liminal", "𔓙"], ["GONYONYAVARIUM", "(can't find)"]]],
["Absolute Fictional Numbers", "◬", "8.00", [["The In-One", "IN𖣮[1]"], ["Improbable Evil Void", "ꬁ"], ["Technologustrial", "◫⤒0"], ["The Photonic Confines", "⌈🜛🜚⌋"], ["FictionForth", "🉥"], ["Swathe Brevardfid", "(can't find)"]]],
["The Endfimidian Breakdown", "[untypable symbol]", "8.01", [["The Ectoplasmic Ending", "✥❧"], ["MAKUNOSHITRIATION", "(can't find)"]]],
["Absolute Celestial", "𓏞", "8.10"],
["HSIWHTAED", "𖤐", "8.18"],
["Armestag Dagenster", "🜲", "8.26"],
["The Galacity Metiorfinien", "[untypable symbol]", "8.35", [["The Googological Edge", "꥟"], ["Deathlock", "央"], ["The Ultimate Monolith", "𓊅"], ["Absolutely Return Numbers", "ret(◬)"], ["Protoversal Polypoint", "⩍⫘"], ["HARITEORBIGOVARATON", "(can't find)"], ["Chromatic Fictitia", "⊹∆<F>"], ["The Escaped Photon", "γ⇛"]]],
["The Godly Rochon-Velotic End", "[untypable symbol]", "8.37"],
["The Alpha-Lλγεr", "α̈", "8.40"],
["The Entri-End", "[untypable symbol]", "8.45", [["The Numerical Edge", "𑁍"], ["The Meaningless Ending", "𖨔"], ["THE RURIRIC VEIL", "(can't find)"]]],
["YAMIRACARKINALITY", "(can't find)", "8.48"],
["The Breakafaunt Pantiltol", "[untypable symbol]", "8.50", [["Absolute Finalitinum", "🜵"], ["The Cataract Opticross", "𓂀🜼"]]],
["The Altar", "履", "8.55"],
["The Absolute Aeon", "𖤇", "8.60"],
["The Masterium", "[☆M]1", "8.65"],
["Succulativiplex", "ꀶ", "8.72"],
["Insurgence", "ꦘ", "8.80", [["The Harmonic Wave of Time", "𝄞∿{⏲0:00}"]]],
["The Section Dialations", "[untypable symbol]", "8.85", [["The Absolute Endless", "ᐉ"], ["The Masteridium", "[★M]1"]]],
["The Ultimatricion", "ᔬ", "8.88"],
["Massive Symbol Sequence", "⧄₁", "8.92"],
["Post-Eternium", "Ϭ", "8.96"],
["Tameuina Tasiaon", "[untypable symbol]", "9.00", [["The Unfathomed Horumber", "ø⌂0"], ["The Hawking Reprise", "黑洞꧂"]]],
["Absolute Orion", "★✪", "9.025"],
["The Duplication", "ꏤ", "9.05"],
["Ascendlutian", "[no symbol]", "9.10"],
["The Realfinitiboxmathaxisfunctionbeyondationoologyabsolutenumberium Ending", "?", "9.125"],
["The Opposite", "≌", "9.15", [["The Parallel Paradox", "𓋣"], ["The [Mastery A - AFN]", "◬𖨮A"]]],
["Absiorcadinary", "⎋", "9.175", [["Spacewarp", "☄"], ["The Ultrafinity", "Ⓤ"]]],
["The Squarefinity", "◼", "9.19", [["SLIGGONIC ENDING", "(can't find)"]]],
["The Backnumbers", "𖢩", "9.20"],
["The Number Circle", "[untypable symbol]", "9.25", [["The Numerically Broken Reality", "ꂸ"]]],
["Omnireality Endless", "ꇼ", "9.275", [["THE CERITERNITY", "⊨"]]],
["Advanced Transcology", "Ϧ", "9.30", [["[Common Number] - One", "RL₁[1]"]]],
["The Transversal Boundary Beyond", "ꃆ", "9.32"],
["The Dark Shadow Level One Cardinal", "ꕸ1", "9.34"],
["Terminal Universe of Integers", "ꂙ", "9.36"],
["THE CORRUPTION", "[untypable symbol]", "9.38"],
["Absolute Liminality", "ꕖ", "9.40", [["THE DEEP BLACK", "⯄⧔⬮⧕"]]],
["ETERNAL LIMINALITY", "ழ⛏", "9.42"],
["T.H.E L.I.M.I.N.A.L", "ꁑ", "9.44", [["THE ABSOLUTE LIMINALITY", "RL₁[1]"]]],
["The L..I..M..I..N..A..L..I..T..Y", "꩜", "9.46"],
["The Word Layer Dilations", "Ꙛ", "9.475"],
["The Final Integer", "ꡭ", "9.49"],
["Ultimus Worldius", "ℕ𖢣", "9.50", [["Forestus Oaktreel", "𖢔⋇0"], ["Premiumized One", "1"], ["HYGIEAN LOOP", "⮤⯚⮧"], ["The Y.U.R.I Of One", "(can't find)"], ["Ultimatum of Lands", "(can't find)"]]],
["Truncated Limitation", "ⰷ", "9.5125", [["Quadtrius Worldius", "ℕ𖢣[…]ℕ𖢣 x4"]]],
["Hyperium Infinitism", "𐌴", "9.525", [["Quintrius Worldius", "ℕ𖢣[…]ℕ𖢣 x5"]]],
["The Aleph-Loop #1", "⟲ℵ1", "9.5375", [["Decitrius Worldius", "ℕ𖢣[…]ℕ𖢣 x10"]]],
["The Absolutium Abstract Googological Abysmal Ending Point", "):&;£;#&", "9.55", [["Centrius Worldius", "ℕ𖢣[…]ℕ𖢣 x100"]]],
["The Abysmal Functionality of One", "⟨A⟩➵x[1]", "9.575", [["Googotrius Worldius", "ℕ𖢣[…]ℕ𖢣 x10^100"]]],
["Absolute Dementia", "𖢒", "9.60"],
["The Leftside", "[←]⍧", "9.675"],
["Zorron", "𐊸", "9.75", [["The Inmastery One", "In-⸭[1]"], ["Ordinion Levels", "€ⵁ‱ / 2-1 (2)"]]],
["Integral Inaccessium", ",∫‟x", "9.7502"],
["Yordashi Constant Capacity", "Ѧ[????[3]]", "9.80"],
["The Impassable Numeral", "𖦠", "9.825"],
["The Galactrion Superena", "𖢋", "9.90"],
["Infinituum Continuum", "℈", "10.00", [["Millom", "ᙢ"], ["Sempiternus Singularitas", "⬙⚵"], ["Cosmosilus Planetarium", "𝕻⋆[↟]"], ["Infinity Fck(a-a)diou", "◽℈"]]],
["The Kinemastery One", "KM⊛[1]", "10.01"],
["Fimu", "𖮉", "10.02"],
["The Absolute Integration", "In∫[TC]^1", "10.04"],
["The Limit Breakage", "LBx[1 | 1]", "10.06"],
["The Laniakea Mathie", "𓀚", "10.08"],
["The Eschatology", "𖨰", "10.10"],
["The Forgotten Matrix", "𖡵", "10.15", [["Transcestrial", "ᤖ"]]],
["Eldritch Immensity", "ಅ", "10.16"],
["The Chaotic Abyss", "[name is symbol]", "10.20"],
["Finitial Existence", "𖡽", "10.30"],
["Low-Endic Eternity", "`ヲ", "10.31"],
["Unrelenting Metatude", "[untypable symbol]", "10.32", [["Cardinal Structure", "⎐"]]],
["Absolutely Massive", "𖢋", "10.33", [["The Masterium [Omegascaled]", "[✶𝕸]1"]]],
["The Galactical Master-Function", "⸬_MASTER||[1]", "10.35"],
["The Endfimidian Finality", "𖤛", "10.40"],
["The True End of Numbers", "►", "10.50", [["BEYOND NEVER", ">[?]"], ["The Quasardinal", "ⶁ⌬ꯌ"]]],
["Cosmictronix", "[untypable symbol]", "10.55"],
["The Nonfictional Altar", "⍦", "10.60"],
["The Rephrasium", "🔂", "10.625"],
["Magical One", "M◇?[1]", "10.63"],
["Absolute Unimplyable", "🝌", "10.64"],
["The Great Filter", "[untypable symbol]", "10.65"],
["The Bypassing of All Numerals", "[no symbol]", "10.75"],
["The Real End of Fictional Googology", "[no symbol]", "10.85", [["Solacitudal Euphoria", "[untypable symbol]"], ["The Everlasting End", "龱"]]],
["Ionatizonis Myocrinthia", "[untypable symbol]", "11.00", [["??BEYOND", "[no symbol]"], ["The Truest Limit of Beyond ?Number", "FG ₸ (2,1,1)"], ["Chaos Endimus", "ꖡ"], ["The Planet to Hold All Numbers", "⌶⧍{1}"], ["Escalantus Correlation", "◈≾"], ["The Elembound Casting", "鼏🝯(🝏)"], ["Point of Cosmosality", "⨁⨝⨁"]]],
["Dynoka Incremina", "Incrementin 2", "11.05"],
["The Universe", "[untypable symbol]", "11.10"],
["Hyperfractizima", "Hf", "11.15"],
["One divided by Zero", "1/0", "11.20"],
["The End of Fictional Numbers?!?", "[untypable symbol]", "11.25"],
["FG ₸₸₸ (1,1)", "[name is symbol]", "11.28"],
["Delt' One Three", "δ{1, 3}{0>/0}", "11.34"],
["The Numerical Gauntlet", "ꡝ", "11.40", [["The Absolute Abyssal of all Ending Googology", "㆙"], ["Demonic Incelation", "ꚠ"]]],
["Delta Totalie", "δƱ", "11.45", [["Real True Penultimate Cardinal", "᯽"]]],
["The Turtle of Numbers", "🐢", "11.46"],
["E.T.E.R.E.V.E.A.M.E.N.E.N.D.N.C.E", "ↅ", "11.48"],
["True Infinity", "☐", "11.50", [["The True Infinity of Milestones", "[no symbol]"]]],
["The Wilderness of Destruction", "☯️", "11.55"],
["Onegafinruom", "[untypable symbol]", "11.60"],
["Numéro Cramoisi", "𐎠", "11.62"],
["Xienas Duetulosba", "[untypable symbol]", "11.66"],
["The Final Overlord", "𖣁", "11.70", [["Absolute Error of Negivtemp", "𝕰⋇[-???ºC]"]]],
["Ifite", "ಲ", "11.71"],
["The R.A.N.D.O.M", "[untypable symbol]", "11.80"],
["The Anti-Descaling", "[no symbol]", "11.85", [["Zoppth Point", "২."]]],
["2nd Zoppth Point", "2২.", "11.86"],
["The Time Collapse", "𐎽☇ ", "11.90"],
["Singulahetti Markie", "[no symbol]", "12.00", [["[NO MORE SCALES]", "[no symbol]"], ["Trescaling", "[no symbol]"], ["Number Line Movement", "[no symbol]"], ["Nil's Number Boosting Hierarchy", "NNBH[x]"], ["Absolute Fractal", "𖥹"]]],
["Inevitazi Definze", "[no symbol]", "12.02"],
["Absolute Crisis", "(symbol lost)", "12.05"],
["Oou", "Ⲱ", "12.06"],
["The End of the FG Community", "[no symbol]", "12.08", [["Reflecto-Never", "𝔹ℕ畜-Π⁰₁"], ["Zaizhirdinal Hypercompletas", "⍾∆(1)ⴙ"]]],
["Absolute Thought-Kounen", "[untypable symbol]", "12.09"],
["The Kalaxology", "𖣡", "12.10"],
["Metempiric Number", "ౠ", "12.15"],
["Hugest", "ꗖ", "12.17"],
["After Time Era", "ATE", "12.18"],
["The Timernlargestgy", "[untypable symbol]", "12.20"],
["The Numerical Nexus", "[untypable symbol]", "12.25"],
["Reoneta Quipedale", "ᕃ", "12.26"],
["Verumfinis Finalis", "ꘐ", "12.30"],
["Honored Typicizal Number", "[no symbol]", "12.35"],
["BEYOND LOE (v1)", "[no symbol]", "12.40", [["Heritability Kalaxial", "𖣡𐌎ハ"], ["Hereditary Postponer", "kハ"]]],
["[ITDOESN'TSTOPBEINGBROKEN] (v1)", "[IDSBB]", "12.43", [["OI[1]", "[name is symbol]"]]],
["<< IMPOSSIBILITY >>", "<<I>>", "12.50", [["The Map Number", "1→(1)"], ["The Starchain", "✯→✯"], ["The Revolving Omniverse", "~⦾↻⦾~"]]],
["Transcendental Zero", "੯ℂ{0}", "12.60"],
["The Shining Star in an Infinite Sky", "𓌯", "12.65", [["Total Eclipse", "⍻○"], ["Numerism Unit Texot", "¹~N¹"]]],
["The Imaginatology", "(symbol lost)", "12.75"],
["The Meteorlogical Point", "▪流星▪", "12.76"],
["The Calculative Breakpoint", "𖨁", "12.80", [["Incontestional Silence", "꛲"]]],
["Absolute Post-Awareness", "𖣑", "12.90", [["The Gratifying End", "〼ꟽ'"]]],
["Transcendental Megami", "[untypable symbol]", "12.96"],
["The Abstract Hypermathematical Point", "𐂶", "13.00", [["Yoru", "夜"]]],
["(FT1?) A_N_E_N_D_I_N_G", "[untypable symbol]", "13.05"],
["The Everyplex", "¤", "13.10"],
["The Infinite Counting", "⍾", "13.11"],
["The Innerspatial Continuum", "ߚ", "13.15"],
["S.X.E.A.L", "𝖷̶𝖷̶", "13.17"],
["Absolute Fictional Cardinal of Numbers", "⎳", "13.18"],
["Inaccessi-Function ~ Level 13", "⦻[13]", "13.22"],
["Skyum Nulloid-Loop", "[❏]_◈", "13.25"],
["The Word-Cyclic Stack", "ȻꞨᱳ[1]", "13.28", [["Absolute Boundlessness", "𖦷"]]],
["The Transector - Null", "𐃐 - [0]", "13.30"],
["TSA(1)", "[name is symbol]", "13.33"],
["The ANNIHILATION of All", "₳+", "13.35"],
["АРАМАЛ", "[untypable symbol]", "13.37"],
["BYLY [2/3]", "[no symbol]", "13.40"],
["THE E※N※D", "≜", "13.425"],
["The Key of Math", "⚿", "13.45"],
["The Numerical Intrusion", "🞖🞺", "13.50"],
["The Cinwenon", "ᆛ", "13.55"],
["InLimitary", "ࠌ", "13.575"],
["Aripiprazole Setplex", "𖼝ℜ", "13.60", [["The End of The Fastest LNGI Ever", "⌧"]]],
["Godiperdinal", "∊❖곧❖∍", "13.61"],
["Transfigured One", "𖨑✺[1]", "13.625"],
["The Grandmaster Number", "𐃙", "13.65"],
["The Apostle of Numbers", "𐂱", "13.70"],
["The Calculium~Breaker", "Abxy⌗FG(n)", "13.75"],
["Pure Zero", "ℙ0", "13.77"],
["The Postwavalology", "⏈", "13.80"],
["Extremitium", "ꀓ", "13.825", [["THE ABSOLUTE NUMBER ENDING FUNCTION CARDINAL", "[untypable symbol]"]]],
["ORDINAL GOODBYE...", "ಊ", "13.85", [["Absolute Impassible Numeral", "ꀅ"], ["Absolution Impassibility", "[no symbol]"]]],
["Absolute Aperdinal (v3.13)", "Ω∈_3.13", "13.90", [["Honored Typicizal Number (Aperdinology Scale)", "[no symbol]"], ["A Finalion of Cosmology", "◪"]]],
["Terminal Exceedness", "[no symbol]", "13.95"],
["The Conceptual Fixed Point", "[no symbol]", "13.97"],
["BEYOND ???*", "Ωϟ", "14.00", [["END...", "⚉"], ["ABSOLUTION HYPERCOSMOLOGY", "⛅︎"]]],
["TRUE END OF BEYOND ???", "[no symbol]", "14.025"],
["The Magixystal", "[no symbol]", "14.05"],
["Endqualizunction", "[untypable symbol]", "14.075"],
["The Kalaxo-Impassable Border", "[no symbol]", "14.10"],
["(FT1?) The Intercological Sanctum", "[untypable symbol]", "14.125"],
["Icyon-Stargio", "𒎓{𖩦}-ឦ", "14.15", [["The Cookie", "🍪"]]],
["Truer Breakdown XXXVI", "[untypable symbol]", "14.20", [["O.U.T.C.A.S.T", "#⇏k"]]],
["Millom (FGW-relative)", "ᙢ", "14.24", [["The Myriad Limit", "万限"]]],
["Ascendency-Bound", "𖧐", "14.25", [["Voidless Desolation", "꛷"], ["The True End of Fictional Googology...", "[untypable symbol]"], ["Tripostwavic Wavalology", "⏈☍⏈☍⏈"]]],
["The Numeriunion", "🟔 - 1⇼1", "14.30"],
["The Cookie Again", "🍪❕", "14.32"],
["Dusolute Infinituum", "Ω口FG", "14.35", [["The (Improper) End of Numbers (v1)", "[untypable symbol]"], ["The In-Fictioned", "[no symbol]"]]],
["Absolute Riftlock", "ꙮ", "14.375", [["The Point of No Return", "[no symbol]"]]],
["The Chosen Integer", "[untypable symbol]", "14.40"],
["Zorron (WUW [21/30]-relative)", "𐩥", "14.42", [["The Episode Breakage ~ TEON", "[no symbol]"], ["Deactione Clapperboard ~ TEON", "🎬~TEON"]]],
["Inaccessible Point of Stella", "[no symbol]", "14.45"],
["THE TRUE ENDS OF THE LIMITS OF THE ??FLOOR(S)…", "[no symbol]", "14.49"],
["The Penultimatum Au Revoir", "𖢰", "14.50", [["The Farewell", "[no symbol]"], ["Thy End of Every Single Fucking Concept That Has Ever Existed And Will Exist Soon", "[no symbol]"], ["SADISM", "[no symbol]"]]],
["The Viscera Divine", "ง𝕯 ⎣⍟⎤ ೡ", "14.60", [["Neverending of Extending Limitational Limiting Ends (N.O.E.L.L.E)", "ℕ⏛"]]],
["Zetalous-Divinity", "⯐", "14.62"],
["The End of Breakings", "[untypable symbol]", "14.65"],
["Aperditoth Fin", "Ω~Є", "14.70", [["The Everlasting Cardinal", "ঢ"], ["Shin2026's Metaverse", ">X"]]],
["The Ultimate Point", "Ł", "14.75"],
["The Uni-Infiminic", "᯼ - (1, 2) {1}", "14.80"],
["THE GRAND UNWAVERING FINAL GOODBYE TO ALL FICTION", "[untypable symbol]", "14.85", [["Spellbound Collapsing Function", "ㄓ₀⦑◰⦒"], ["Pixel Perfection", "𝓹𝐀⇥⦑𝐀⦒"], ["The Takeoff", "[no symbol]"]]],
["QUASIEND OF TOXIC EXTREMES", "[no symbol]", "14.90"],
["PROXIMA CENTAURINION", "[no symbol]", "14.92"],
["THE ABSOLUTE TRUE END OF FICTIONAL GOOGOLOGY", "[untypable symbol]", "14.95"],
["LUCIDITY", "ℒ", "14.962", [["Luminosity", "[no symbol]"]]],
["ฯθ|Ω©£\×;!(", "[name is symbol]", "14.975"],
["THE END OF ENDINGS", "[untypable symbol]", "14.99"],
["The Snowgrave of Numbers", "[no symbol]", "14.999"],
["THE TRUEST ABSOLUTE TRUE DEATH OF EXISTENTIAL IMPOSSIBILITIES", "[no symbol]", "14.9999"],
["Eternity", "֎", "15.00", [["THE (false) END OF NUMBERS (v2)", "[untypable symbol]"], ["Anti-Vacuum Hyperspace", "∅⌘"], ["The Absolute Eucharism", "ဧᥫᐁ"], ["Standard Limitment", "[untypable symbol]"], ["Endonumeria", "𖡭"], ["The Optical Finality", "᳀"], ["Celeritas Lucis", "[untypable symbol]"], ["The Glimpse at Peril", "[no symbol]"], ["Hypnocampus", "꩜_脑"], ["Disobey the fictional googology", "(can't find)"]]],
["The Ultcrossful", "†", "15.0002"],
["Absolute Destructuoation", "ꘚ", "15.001"],
["LETIBICUS VORICIAN", "ℕ𖤍", "15.002"],
["Astralix Finomniea", "𞄈", "15.003"],
["Absolute Penrose", "𖤽", "15.004"],
["I N A E T E R N U M", "𝀵𝁟", "15.006", [["Numismatics Browbeatikil", "(can't find)"]]],
["Enhance Mastery I", "E★(1)", "15.0061"],
["Heliconiusic Fgiskiipoint", "𖡷𖣣", "15.008"],
["PHYSIALIS", "꡵", "15.01"],
["Ultimated loop #1", "[no symbol]", "15.0103"],
["TOTAL MOTTEENDING", "𑈂", "15.011"],
["Ascapelpi-Numerinia' Unsureity", "𑩢𑪄", "15.013"],
["Absolute Breaking of Numbers", "∮", "15.014"],
["World Border of All Numbers", "Σ∏∏⨲N𝄋≠░𖢻⍰", "15.015"],
["The Finalety", "⌬", "15.016"],
["D.i.s.h.e.v.e.l.e.d", "(can't find)", "15.0175"],
["The Final Polstokiinumberinia", "⎈", "15.018"],
["THE ABSOLUTE FUNCTIONS", "🆇", "15.019"],
["C A E L", "[untypable symbol]", "15.02", [["CHUKOTIK (v2)", "[untypable symbol]"], ["Roponiccho's Number", "ᆐ"], ["Fictional Limitment", "[untypable symbol]"], ["Celeritas Tenebris", "[untypable symbol]"]]],
["The Amoniac", "±", "15.021"],
["Gempaticket", "𝆱", "15.023"],
["The Neutramipe", "⍻", "15.025"],
["The Chylabyrospast", "𞄢", "15.0275"],
["Aperdilute Endinlevel", "[X]_[X]", "15.03", [["Absoluteileal", "(can't find)"]]],
["The Non-Existent Finality", "(can't find)", "15.032"],
["Timbletes", "𞋁", "15.034"],
["Infinititlimanpy", "[1𞋍]", "15.037"],
["Dlistion", "ᬋ", "15.039"],
["The True X", "🅇", "15.041"],
["Bardolion Stage 2", "ꥃ[2]", "15.043"],
["The Grandtriuina Limit", "𑢽", "15.046"],
["Never-Ending", "〒", "15.048"],
["Unworldly Loop #1", "1𑴦ꕕ", "15.05", [["Third Stepisk Au Revoirun", "[untypable symbol]"]]],
["Unpromisity", "ჶᅧ", "15.055"],
["Tevicalicity", "ꤡ", "15.06"],
["Overquotalfinita", "[untypable symbol]", "15.065", [["Finaticoid Point of Ends", "꛶"]]],
["The Numerical Overcluster", "◇C_□!", "15.07"],
["Ardomation", "!ꛚ!", "15.0725"],
["The Hyalop Principle", "[untypable symbol]ୟ", "15.075"],
["Absolute Time Skip", "ⵣ{Q}", "15.075"],
["Periosecond", "⏍p", "15.08"],
["The Arch of Numbers", "ǂ", "15.085"],
["Bombycida", "[untypable symbol]", "15.09", [["Borosilicate Loop", "(can't find)"]]],
["The Limical Trianglum", "△⇧", "15.0906"],
["LIMITORNAL", "κ°", "15.09125", [["Evasive disownment", "(can't find)"]]],
["The Insideness", "𑫮", "15.092"],
["Dinamentrex", "𒍄", "15.0925", [["Disobeying Bonaventure", "(can't find)"]]],
["The Devendranial Mottenis", "[untypable symbol]", "15.095", [["Slute Die", "(can't find)"]]],
["Hypernate Function Array", "M(1)/(2)1 𒍦 D(1)^1", "15.099"],
["Absolute Aperdinal Pi (TAEoG-relative)", "Ω∈_π", "15.10", [["Brokelute Googology", "[no symbol]"], ["The Hyperium Diamond", "ℍ~◊{1}"], [" Ground Zero", "⤓_0"]]],
["Endolum Catastrophium", "ꤡ", "15.105"],
["Type 2 Lidu", "Ṭ ° (2)", "15.106"],
["ENDOFALL", "[no symbol]", "15.11", [["Snowboarding One", "(can't find)"]]],
["The Swooned Point", "§§§ [§]", "15.112"],
["The Synthetic Disobedience", "[untypable symbol]", "15.114"],
["Absolute Deterrence", "⤰?", "15.115"],
["The Absolutest senate", "(can't find)", "15.116"],
["Superfinity (Superscaled)", "S+", "15.118"],
["Þŕæñßfįŋíţƴ", "Ꝏထ∞", "15.12", [["Sublimity", "[untypable symbol]"], ["The Superena of Redacted", "𒁜"], ["Resetili-Sicity Eucaris", "[no symbol]"], ["Supraflow", "+≋"]]],
["The Ending-Eternal", "◮_End", "15.125"],
["Chrona Beyonum", "Δ+", "15.13"],
["Infility", "ι{∞}ι", "15.135"],
["(!!) Arkinatium of Veracity", "ᚻ_ᗗ^1[1]", "15.14"],
["Apeiropause", "κ_∞", "15.15"],
["Celeritas Tenebris: True Glimpse", "[untypable symbol]", "15.152"],
["The Convergence Ologism", "口{...}G", "15.16", [["RESONATION", "⥀^∀"]]],
["Celeritas Lucis: True Glimpse", "[untypable symbol]", "15.17", [["Absiunator", "ဿ"]]],
["Absolutum Extendlim", "[no symbol]", "15.18"],
["The Celestial Commandment", "ପ␑", "15.20", [["The Last Bow", "☆"], ["The Timeless Kial", "ធ"], ["N0TNO p10", "[no symbol]"], ["Quetzlcoatl", "ℚℚ"], ["The Great Finitarium", "⦏Finitary⦐ 1"]]],
["The Finitial Finale (v1)", "⚞⚡︎⚟_1", "15.225"],
["Versionological Finalion", "𐄩𐄷𐄩", "15.23", [["Thypen-Supperaction", "Thy[1]"]]],
["Quasionic Structura", "ℚ♗𐙤𐁅", "15.25", [["Fin.Nihil ~Aeternitas~", "ʧ★"], ["The Last Dance of Numbers", "[no symbol]"], ["HYPERTENSION", "(undecided)"]]],
["Apeirofinite Catadestruction", "☲", "15.26"],
["The Finitial Versi-Finale", "⚞⚡︎⚟_5", "15.265"],
["Outerrealmic Mitochondrion", "Ǿ_𖥓", "15.275", [["The Aeonic Veil", "⧋"]]],
["𝔹 𝔼 𝕐 𝕆 ℕ 𝔻  ℝ 𝔼 𝔸 𝕃 𝕀 𝕋 𝕐", "[no symbol]", "15.28", [["ALL ENDS NUMBER", "[no symbol]"]]],
["🦀 this crab is raving in ur entry!", "[no symbol]", "15.29"],
["THE TRUEST ABSOLUTE TRUE EXISTENCE OF ROYAL ETERNITY TO EVER EXIST IN THE TERMINUS FINALITY EVER", "[no symbol]", "15.30"],
["TERMINAL FUNCTION", "[untypable symbol]", "15.31"],
["轮回渐进函数 (Cyclic-Progressive Function)", "[untypable symbol]", "15.32"],
["Abstractum Deffecailia", "ꩇ", "15.33"],
["Spriliasacunon Allcomplex", "[untypable symbol]", "15.335", [["Primordius Ultimiad", " ꦺ"], ["Everything Scapa", "[untypable symbol]"]]],
["Theoretic-Exclusivity", "(undecided)", "15.34"],
["The Absolute Grand Finale of all Versiontomin (Notation) and Versionology", "[no symbol]", "15.35"],
["Osiris Legandria", "[untypable symbol]", "15.36"],
["The Finitial Finale (v7)", "⚞⚡︎⚟_7", "15.375"],
["Absiunator", "[no symbol]", "15.38"],
["The Clock is Ticking.", "[no symbol]", "15.40", [["Alveniza Class 2", "ᤂ[2]"]]],
["Omnempiric Number", "[untypable symbol]", "15.42"],
["Lost.", "(undecided)", "15.425"],
["Superexistential Cetanumker", "S_∃[쳍#1]", "15.45", [["The Second Coming", "ጥ셏2촘"]]],
["Vespa Spectre Isolation", "[untypable symbol]", "15.47", [["The Beyond Classifications", "ꦜ⍰"]]],
["DARRACHOLIUM", "ᥖ", "15.49"],
["ApG-DØS I-Mysterker", "🈭Ø^?", "15.50", [["Omegastageitology", "Ꝼኦſଓ"], ["True Cycle 2", "[no symbol]"]]],
["Enhancation Ritual Number", "⧝∑⇌ ", "15.52"],
["Common Mastery #1", "Ꮳ[1]", "15.54"],
["Oneiric Ineffability", "(undecided)", "15.60"],
["Numxer Starlineum", "ᆇ✦⩤1⩥", "15.70", [["Finitial Regiment 2", "𝖁⟪F⟫#ℜ₰₴[2]"]]],
["The Absolute", "[untypable symbol]", "15.75"],
["THERE IS NO GOAL. (LENS-relative)", "[untypable symbol]", "15.80", [["The Absolute Nova", "(undecided)"]]],
["Planck Versio-Constant", "𝖁[ℎ]⸢0⸥", "15.825", [["Temporal Altrascendum of Negative Zero", "Å_੮(-0)"]]],
["The Special Ending", "[no symbol]", "15.875"],
["Ascendental Paradise", "៳", "15.90", [["Zero to Zero", "[0,0]"]]],
["The Great Communium (v1)", "ϐ_v1", "16.00", [["Archaea Volcanis", "ꖰ"], ["The Monarch Number", "(undecided)"]]],
["The Limit of Series", "¶", "16.01"],
["The Silent Starnation", "Ꙟ✮", "16.02"],
["The Shadow Blinder Limit", "[untypable symbol]", "16.05", [["NOLIMITEND", "ʄ"]]],
["The Dyslexic Synchron", "[untypable symbol]", "16.10"],
["Absolute Chapter Sequence", "ꦌ§[1]", "16.13"],
["Absolutei' Analogitae", "ⴀ᱑႞⦗൜⦘൸☍옾", "16.15"],
["The USB Stick (First Appearance)", "💻 ", "16.19"],
["The Déjà Vu Loop 1", "J(can't find)(1)", "16.21"],
["The Limerence Ending", "🝁", "16.25"],
["The Unforgettable Memories of Transcendentals (Intended scale)", "ℌ੯ℂ►︎🛇", "16.30", [["ABSOLUTE SECTOR LIMIT", "[no symbol]"]]],
["Motonerich Ascalotium", "ᱶ", "16.33"],
["Quattuorcurveitology", "൜[4]", "16.35", [["Nirvanae Seraphumber", "𝔑✟₀"], ["The Meterium Diamond", "𝕄~◊⦃1⦄"]]],
["Preultimate Ascanded", "𑗕", "16.371"],
["Anthephropis Symmetricumelo", "[untypable symbol]", "16.385", [["Paradimaxion", "꧁1꧂"]]],
["The Frontier of Versiontomin", "[equation]", "16.41", [["Ceolatornical Radiocollapsium", "𐘜𖺚𓍀𐘜"]]],
["VERSO NUMÉRICO SIN RESOLVER", "[untypable symbol]", "16.425"],
["Infinityium", "{Ø∞~}", "16.44"],
["Fictional Obliteration", "{{۞Ø央x?}calc.}", "16.48", [["Antiversal Horizon", "Ꜻ"], ["Eternityium", "{ØΔ~}"]]],
["Quantumium", "{ØΨ~}", "16.525"],
["The Drawback Disobedienium", "(can't find)", "16.60"],
["Absolute Cyclutic", "C꦳[1]", "16.64"],
["Seasonix-Dilation", "ߟ", "16.89"],
["Fictional Googolo-Memoriam (WUW-relative)", "x_x", "16.90"],
["THE CLUSTEROUS SYNCHRON", "[no symbol]", "16.91"],
["Nullbox", "❒^ℵ", "16.95"],
["THE TELEMIATA SYNCHRON", "[no symbol]", "16.98"],
["⏰* The Zyrolexic Synchron", "[untypable symbol]", "17.00", [["The Corrotechnic Gameshow", "Ҳ☏⡟⁼"], ["Complex Nonrecursion", "(undecided)"], ["STARSTRUCK", "✦_ᐰ𑿯"], ["The Holy Call of the King", "[untypable symbol]"], ["The Hyestrical Monarc", "☧Ⳛ"]]],
["The Unlimited Ending", "⦗𝕍႒⦘", "17.05", [["Absolute Starglass", "[untypable symbol]"]]],
["HELLISH", "[untypable symbol]", "17.10"],
["Postversolute Xiligatie", "⦗𝕍႓⦘", "17.15", [["The Fictisor Boundless", "[untypable symbol]"], ["THE TRUE EVOLUTION LIMIT", "[no symbol]"]]],
["The Voyage of Fictional Googology (TAEOG-relative, improper)", "[no symbol]", "17.20"],
["Trythingent Extromoldium Ratraofveines", "[no symbol]", "17.23"],
["The Continual Rift of All Versionology", "⦗𝕍۝⦘", "17.25"],
["The Superlunary Numerical Limit", "ឍ𖢲", "17.30"],
["Lucasfinity (Sky's Variant)", "[no symbol]", "17.35"],
["Truer Breakdown XL", "[untypable symbol]", "17.39"],
["⏰* Inconclusive Astrintua", "[untypable symbol]", "17.40", [["Ending of Versiontomin", "𝓥⪋E⪌"], ["The Abserract Final Ends of Numbers", "༩"], ["The Determined Voidbound", "⋆°♡࿔"], ["The Avant-Dernernius Empyreal", "[untypable symbol]"], ["Eternitital Binaryl", "Ⳡⳣ"]]],
["The Push", "ꖦ", "17.42"],
["Polyclassic Corrofictional", "Ҳ☏➳✧", "17.45"],
["Corronumkerical Massivity", "⋻ 1 ➳ 2 {Ҳ☏}", "17.475", [["The Seasonskip Loop #1", "Şཉ(1)"]]],
["Omnightum Hyprabreaker", "𝍈⇓Δ", "17.49"],
["First Applical Ordinal", "ⓐ_∆[1]", "17.50", [["The Actual Limit of Fictional Googology (no v4-B) (aka. Absolute Actualility)", "ꄥ / 𖡞 / ꈯ"], ["The Insurmountable Ficto-Googological Mountain (no v4-A; lower bound)", "⧊^"], ["The Finitial Finale (version-independent)", "⚞⚡︎⚟"], ["Corrotechnical Fatality", "☏➳Ҳ_Ҳ"]]],
["Ocizag Level 2", "ꜷꜥ[2]", "17.54"],
["The Absolution Finality", "< !-END-! >", "17.55"],
["Corrotechnical Apeirodimensionalia", "Ҳ☏Є⧞Э", "17.575"],
["The Perfect Grand Finale (no v5)", "< !-LASTING-! >", "17.60"],
["TIME DECAY", "ʋ", "17.61"],
["Absolutinoic Foreverance (no v6)", "ꗴ", "17.65"],
["Absolute Endigomen", "ဏ္ဍ", "17.69"],
["Absolute Calamity (no v7)", "𖢺", "17.70"],
["ENTYRILPLEX", "ꠀ", "17.76"],
["Limit of the Night Sky", "☾⤻✭", "17.80"],
["The Reinfoundous Number", "ꢛꝍꟽ[1]", "17.83"],
["The Realitus Unworldly Meta-Ending Goodbye of Fictional Episodes of Everything of the Goodbye and Universal Explosion and Everything Ends for Everyone in This Reality and Beyond Hyper Ending Goodbyes of the Ultimate Unknown Undefined of Absolute of Fictional Numbers Everlasting of Gorgeous Ends of Absolute Destruction of Finals of Numerical Sequence of Transcending and Ascending Ultimation of Nothing and Universal Fictionality Transcended and Ascending of Fictional Everything Unworldly and Everything Exploding of Every Number in the Multiverse Beyond and Reality Beyond Ultimate Numbers of Ending of the Repeated Unknown and Undefined Overscaling of Fictional Universes Ever in this Reality of Ascending Beyond Unworldly Numbers Ever in this Restart Shut Down and the Beyond Universe Hyper-Infinite Endless Scale of Goodbye Transcended Restarted Universal Reality Everlasting Godlike Unworldly Meta-Ending Breaking Episodes and Beyond of All Numbers", "[no symbol]", "17.90", [["Tebow Continuosity", "ꢉ"]]],
["Bosworth finality", "[untypable symbol]", "17.92"],
["The Stonebridge of Numbers", "⚜️", "17.922"],
["The Viera", "💠", "17.924"],
["The Avros Sharpsburg", "〽️", "17.925"],
["The Viana Barbara", "⚛️", "17.926"],
["Megaloblatta Longipennis", "📐", "17.927"],
["V-o-e-g-e-l-e", "[untypable symbol]", "17.93"],
["Network Disaster Management", "🥅ð", "17.931"],
["Cetacomb’s Number", "(can't find)", "17.933"],
["SEARCHED PHNILEIUS OF EASTWOOD DISENGAGEBRR", "[untypable symbol]", "17.936"],
["GOOGLE", "G", "17.937"],
["Alcathemsten Floridinium", "(can't find)", "17.945"],
["The Servant of Googology", "[untypable symbol]", "17.949", [["Hesston Helicopters", "(can't find)"]]],
["GECATSYA PENSACOLA OBSOLUTION", "(can't find)", "17.9495"],
["The Final Culmination", "[untypable symbol]", "17.95", [["OpenBetelgeuse", "[☀️]"]]],
["The Nauru Plural", "☀️/⚔️/ღⁱ", "17.956"],
["Hersheypark Browbeat", "[untypable symbol]", "17.96"],
["The Grim Final", "뿿", "17.98"],
["Celestial Embodiment", "(can't find)", "17.985"],
["HELLSINKI", "(can't find)", "17.99", [["THE TRUE", "[untypable symbol]"]]],
["HESITANTLY JAVASCRIPT NUMBERS", "(can't find)", "17.995"],
["Truer Vexing Browbeat", "(can't find)", "17.996"],
["YPSHVENGDENERO", "(can't find)", "17.997"],
["The Creator of All Fictional Googology Numbers", "[untypable symbol]", "18.00", [["Gradient Unit", "[no symbol]"], ["no (version-independent)", "[no symbol]"], ["All-Form Limit", "₳⍉ꊝ"], ["The Corroultimate Culmination", "⦑Ҳ☏⦒~Ø~⦑⡟⁼⦒"], ["Metropide Calibra", "[untypable symbol]"], ["The Eternal Midnight", "☼(0:00)"], ["The Demisal Invoid", "🝱"], ["FakeAdsBlock", "[untypable symbol]"], ["Photometric Polyactism", "ঐ⦿"], ["Choiquol Maichium", "ↇ⮛↥"]]],
["Second Zero (upper bound)", "0₂", "18.005"],
["The Numserbook", "ጢ", "18.01"],
["NIUE", "[no symbol]", "18.025", [["Hyper-Dexametric Failure", "F͓̽~⚞χ_χ⚟"]]],
["Absolute Absolution", "Ꜳꜳ", "18.027"],
["Numwer Graveyard", "❡", "18.03", [["Hyperbolinium", "[untypable symbol]"]]],
["Jumner One ", "∞₁¹", "18.04"],
["The Cyclardinal Limit", "[untypable symbol]", "18.05"],
["The Imperial GODLIKE Power Of Numbers Strength and Will", "⚠|★|♛|★|⚠", "18.055"],
["Ocpulus Syndrome", "Ꮹ", "18.06", [["The Dexametrical Fate", "X=⚡︎X"]]],
["Acsilitry Infilitry", "ღⁱ", "18.07"],
["The Concept of a Klumager", "🜹", "18.085"],
["The Reborn Number", "[untypable symbol]", "18.10"],
["The Further End of The Great Communium", "TP-EO[ϐ]", "18.11"],
["The Reality Core…", "Ꙩ", "18.12"],
["The Real Reborn Point", "[no symbol]", "18.135"],
["Googol-o-Numxer", "[untypable symbol]", "18.15"],
["Outerspace Hyperset", "⍚✶⑆", "18.20"],
["The Fictional Googologism (yes v1)", "ꄝ", "18.25", [["The Lightniant Erratus", "[untypable symbol]"]]],
["Final Gradient Unit", "[untypable symbol]", "18.30"],
["The Alpha-Numerical Monarch", "[untypable symbol]", "18.40"],
["Vark", "ॡ", "18.41", [["Eternis", "Ʀ"]]],
["The Implicit Edge", "ꭡ", "18.43"],
["Limits of Beyond", "ꕅ", "18.45"],
["The FG Barrier", "ƕ", "18.48"],
["Theraperdinae Timelineus", "[untypable symbol]", "18.50"],
["The Inaccessible Goal", "Î", "18.52"],
["The Symber", "🙱", "18.66"],
["The Fictional Masterium", "[🌠︎𝓜]1", "18.71", [["The Hyperionic Endinite", "[untypable symbol]"]]],
["The Subeuclidean Realism", "❮≠ℜ❯♦⇦", "19.00", [["The Historic Void", "⏱︎_◌"], ["The Mutant Sanctuary", "Ց"]]],
["Askerengus Hyxpea", "[untypable symbol]", "19.025"],
["Breakologus Googoregous", "[no symbol]", "19.10"],
["Fictional Googolo-Heavenium (N0tBTT-Relative)", "Y_Y", "19.111"],
["Texinasuration Exali", "[untypable symbol]", "19.14"],
["The Post-After Endtime (a.k.a. The Mathematical Breakage)", "∀±", "19.17"],
["The FG Breaking Point", "[untypable symbol]", "19.20"],
["Absolute Communium", "⫛ϐ⧨", "19.25"],
["Realityfinitum", "႟", "19.27", [["<|< TRANSCENDENTALISM >|>", "[untypable symbol]"], ["Mira Rumi Zoey", "[untypable symbol]"]]],
["Surrealismic Euclidanx", "[untypable symbol]", "19.30"],
["Deinsaned State 2", "DX鱤[2]", "19.31", [["THE END OF KPOP DEMON HUNTER", "[untypable symbol]"]]],
["Thy Crysta' Luna", "𑇍", "19.32", [["Amoris Numkerical Ruby", "₊˚𝔸𝕞ℕ𝕜𖢻˚₊"], ["xyl", "ᨮ꫶ׁׅ֮ᥣׁׅ֪"]]],
["The Ossining Highness", "곡", "19.34"],
["Ascendilizium", "ꬄ", "19.35"],
["Maximorgolous Infiniinun", "[untypable symbol]", "19.38"],
["ORSZÅG HEAVEN", "[no symbol]", "19.40"],
["The Pedestrian Number", "ᶂᵳ₋₀", "19.50"],
["Resolute, Ultimate Eradication", "ᔐ⤓┤Ł├⤒ᔐ⭁", "19.60"],
["Limitalifinity", "Ŧ", "19.64", [["BAYMAX", "[untypable symbol]"]]],
["Varkinson Numillo", "V₀𖠊[1]", "19.70"],
["The Final Number... Forever.", "☬", "19.71"],
["The Dangerous Transcendence", "𑄑", "19.713"],
["The Adversal Osmosis", "𔓃𓍊", "19.72", [["CHANCE", "[untypable symbol]"]]],
["Omniumber One of ???", "Ꙋ", "19.725"],
["The General Dynamics", "𐃲", "19.728"],
["The Every", "₰", "19.73"],
["The Xenophysical Grid of Nothingness", "ᚻ▦Ø", "19.75", [["THE SAMMY", "[untypable symbol]"]]],
["M E D I O C R E", "𝇑", "19.84"],
["The Frigid Zone", "ଶ¦ୱ", "19.87"],
["Ethereal Zero", "𝔈𝔱{0}", "19.95"],
["Dimiourgós of Unbounded Mathematic Chronologies", "[untypable symbol]", "20.00", [["SERAPHUNITY", "[untypable symbol]"]]],
["THE XENO", "[untypable symbol]", "20.02"],
["Geonebulae Calamis", "星云", "20.03"],
["The Patientha Cycalcanationation", "ꤟ", "20.04"],
["Cwestionable Conundrums", "☆[;", "20.05"],
["Girli-Terfynol", "A-🎀✭✶", "20.06"],
["The Unknown Compution", "�⃣", "20.065"],
["Onerous Redshifton", "ð ¬ ⟨1⟩", "20.07"],
["Dynastium Gigaparsec", "[untypable symbol]", "20.08"],
["The Numero Dynastium", "⧃⌭:⥵", "20.09"],
["Ultimate Insanity", "Ⱦ", "20.10"],
["Millennium Bug", "ꭚ2ꞣ", "20.11"],
["Terminological Zenith", "[untypable symbol]", "20.13"],
["Finalion The Fiction", "ꫀ̸̨̛̭̤̩̳͎̲͚̪͈͜ͅ", "20.14"],
["THE.x.x.END", "[no symbol]", "20.17"],
["THE FINALOMIGHTY", "[no symbol]", "20.19"],
["The Numbery", "☊", "20.20"],
["The Final Universe of Numbers", "☽", "20.21"],
["The Universal Breakage of Numerals Forever in the End of Time And It All And We All Know Itends Here in the Time of Ending And Fictional Numbers End Here of Fictional Googology Memoriam Ending of the Finale of the True Ends That Will Now End at This Absurdly Gigantic Number", "❍", "20.22", [["Computionalic Ultrino", "⛝↹0"]]],
["OKAY Sea Dream World", "[untypable symbol]", "20.23"],
["Arithmetical Dilemmas", "༖", "20.24"],
["The Forgettor", "ග", "20.25"],
["Numberia Finali", "Ѭ", "20.27"],
["Kosolute Escarnial", "씳ƛ⎰1⎱", "20.28"],
["Áǝthǝrion Libǝratia Expansǝun of Étérnal Ascændantium", "[untypable symbol]", "20.30", [["The Golden Temple of Math", "𓉤"]]],
["Dreamescape End-Maker", "𖧊", "20.305"],
["Ibrat Kardinalz Limit", "I֎𐫂", "20.31"],
["Space-Timeic Enigma", "⎘", "20.315"],
["FAR REACHES", "ఊ", "20.32"],
["Universa-Compact Endiversus A", "A۝", "20.35"],
["The Fading History", "𐜗", "20.36"],
["Function Assembly Line", "Ǽ&Ǽ&⎰Ǽ⎱", "20.37"],
["Tetrafounded Dumbthough", "ॐ", "20.38"],
["ANDITHUS", "ᅕ", "20.40"],
["OPERA CONVULSIONS", "[no symbol]", "20.41"],
["Polydamas Hypotheticalitium", "ᬨ", "20.42"],
["Hyper Aethereal", "[untypable symbol]", "20.43"],
["Gaeaion Endibound", "[untypable symbol]", "20.44"],
["Hyperspace Fabric", "𖡎", "20.45"],
["Uno-Poweri'U'Numero Fikton", "[untypable symbol]", "20.46"],
["Beyond The Stars", "꧅", "20.47"],
["The Metarhetorical Thought", "[untypable symbol]", "20.48", [["Chasmitinitial Dischargia", "Ⴥ⫺㋔⫺"]]],
["Demopolisic Arithyms", "𖭜𝚩ᎄ", "20.49"],
["Metahistorium", "𖹓", "20.495"],
["Realituum", "⥪⒭⥭", "20.50"],
["The Sacred Number", "⛜", "20.52"],
["Treaty Inferno", "[untypable symbol]", "20.525"],
["Ilfinitii Radix", "⍼", "20.53"],
["Karakraric Heyzoceyrysm", "[untypable symbol]", "20.55"],
["Copaxa-Entry Infinity", "⟪ᰄ⟫ [0][1]", "20.60"],
["Definitia-Quotax", "ភ", "20.65", [["The Disengaged Masseaveurlenche", "[no symbol]"]]],
["Finalium: A'A", "A◌ᬶꩇ.܍◌ᬶA", "20.66"],
["mere fragments of bliss.", "℘ꌗ𝖙ᧁ<┗100┓", "20.665"],
["Quanji Xenokumbpi", "ዟ", "20.67"],
["Supraperdinal Ingin", "[untypable symbol]", "20.68"],
["The Reversal's Oracle", "🝰_0", "20.685"],
["Mortiferous Enumeration", "☥a⚰︎⟆", "20.69"],
["Perennial Subtlety of the Mind Eternal", "[no symbol]", "20.70"],
["Bunaea Alcidonea", "Ꮦጂ", "20.72"],
["F.I.C.T.I.E.J.S", "𝖂", "20.73"],
["Tranquilized Serenity", "ᕲ", "20.74"],
["Alnitak Damage", "✦⭑⭑", "20.741"],
["Powertynia", "վ", "20.76"],
["Honum Fissiyunds", "[untypable symbol]", "20.77"],
["Aestenen Koncept", "Ӭ", "20.78"],
["Difficultarion Loop 1", "ᦤ", "20.785"],
["Rishfkransek Terminator", "R//2", "20.79"],
["SIKE, IT’S MORE PURSUIT!", "℘Čℓ𝓈<┗2┓", "20.80"],
["The Metaness Number", "[no symbol]", "20.81"],
["Honjum Fisqayunds", "[untypable symbol]", "20.815"],
["Absolute Decompression of Numbers", "-ဉ-", "20.817"],
["Divinity Transcedurance", "Đ﴾𝜕ℾ", "20.82"],
["The Quantum Maglioxa", "𖨮", "20.84"],
["Quattro Penultimata Livazia", "ꯑ", "20.843"],
["THE POST-PURSUIT ZONE", "┗1┓}┗10┓", "20.85"],
["An Endless Façade", "…∞⤪ꝼ⤮∞…", "20.875"],
["The Roaring Darkumber", "[untypable symbol]", "20.90", [["THE PASTPREFIX ERA", "┡✞⋽"]]],
["The Glitchahhada", "GĹ<1>", "20.92"],
["Hydraceleste Elixirdinal", "❄", "20.946"],
["a blissful ending.", "[no symbol]", "20.95", [["Cryogzak Maxionara", "[untypable symbol]"]]],
["Caviouslimity", "ꚥ", "20.958"],
["Buhid Loop", "ᝆ", "20.96"],
["Multrisemnia", "◙", "20.97"],
["Grancelesto-Kommunal Downfall", "[untypable symbol]", "20.981"],
["bliss.", "⦓𝒷⦔", "21.00"],
["The Recoversal", "ᘝᖇ☩", "21.001"],
["The Mastery Emblem", "𝑴ଲ{2}", "21.005"],
["The Final Disenfranchisement of Every Number", "[untypable symbol]", "21.01", [["Dimensional Hierarchy", "[untypable symbol]"]]],
["Telemiata Cataclysm", "䨺", "21.02"],
["Arcanum o'la Imperial Summatic Veritas", "[untypable symbol]", "21.05"],
["~( STARTRINITY )~", "[untypable symbol]", "21.10"],
["Nythria", "[untypable symbol]", "21.11"],
["The Metaness Function", "ξ{2}", "21.12"],
["Last Au Revøir - of Digits", "[untypable symbol]", "21.14"],
["Xevact-U-Levelecixium", "𝐮^𝛩+𝖃", "21.145"],
["The Transmundane Infinity", "ꍇ", "21.146"],
["The Mythological Eternity", "𐙁", "21.15"],
["The Infanumbrue", "𝖃𝛩ᵥ₁", "21.17"],
["The Stardazed Divinity", "𝄇✡𝄆", "21.20"],
["The H.Y.P.E.R.B.O.L.I.O.N", "Ҵ␀", "21.25"],
["Verustic Realism", "[untypable symbol]", "21.35"],
["THE EDGE POINT OF NUMBERS", "[untypable symbol]", "21.50", [["The Numerical Sanctuary", "[untypable symbol]"], ["Oneoido' Fictionalia", "Inf₁{1}"], ["Breaking of Thecore", "BOT[????]"], ["Omegana", "Ōऋᄬᅶ"], ["ASTRAY NUMERICAL CHAINS", "𖩖"], ["The Gramia-Limit", "(can't find)"]]],
["Endlesso' Fictionalia", "Inf₁{ᚖ}", "21.51"],
["Defcon Six", "ÐËဨ⌈6⌋", "21.525"],
["Halfline of Neutronium", "Ҵଜ/1/", "21.53"],
["Gorduan Refragmentation", "ᝦ", "21.54"],
["The Technical Blade", "ﾒ_刀𓍝", "21.542"],
["The Untimaning Request-Levelicity", "ᛑᢕ", "21.55"],
["The Circled Zero to the N", "⓪ⁿ", "21.563"],
["The Unreliable Ecosystem", "𛱵𛱙", "21.57"],
["X-Dimensional Kollapsement", "Ⳛ_ə⿒^й", "21.58"],
["The Lunarølogikal Underflow", "ΞǼ^⫛Ξ", "21.59", [["Transmudane Finale", "ア隘「ォ栩隨カ供k7ァv"]]],
["Interformational Finity", "𑒀", "21.60"],
["Ecsipronto Partitioning", "Ꮙ", "21.61"],
["The Aphasic Hyperstructure", "𝔸", "21.625"],
["The Tachyon Expanse", "ⴴϯ", "21.64"],
["Exoelemental Transpotential", "℣Ⰳ", "21.65"],
["Clarified Symboliunira", "🗗", "21.655"],
["The Null Constant", "_", "21.66"],
["THESALES-TRANSRELIVIAN NUMBERS", "[no symbol]", "21.68"],
["Pseudocosmic Carinae", "𑖇𑨦", "21.70", [["SERAPHIVORCE", "𐑗"]]],
["Caxet Demonstratum Parallellity", "𞊕𞊗ꀡ", "21.725"],
["Absolute Quakers", "≌⎋ᙢᤖ", "21.75", [["Precise Virtualized Continual Values", "᭻ᮅ"]]],
["Aperikalute Transaperdinal", "Ѧ^2𖠄", "21.77"],
["TIMELY-HUIDOSIC COSMOGONY", "[no symbol]", "21.775"],
["THE INNEZO", "🜶", "21.80", [["The Black Hole of Numbers", "⧗○⧗"], ["RHANDORMEN SCRIPTURE CLOSION", "𓉶𠁆"]]],
["Cata-Prospector", "ϾФ_∂", "21.815"],
["The Integer-Precision Standpoint", "𝕊(𝐼𝑛𝑡[_൫0])", "21.82"],
["GLOBALSTAR-LAXXINATIO", "𐃸𑖂", "21.825"],
["Quectant Retrofinite Chain", "𒿘𑖋(1)", "21.86"],
["THE FAUX AETERUANIELS", "[no symbol]", "21.885"],
["Chronodynamis Gateway", "[untypable symbol]", "22.00", [["The Creation Altar", "✐⿈"], ["The Transperdinal", "⍾"]]]];
console.log('numarray imported');
